name: Build Dev
run-name: ${{ github.event_name }} triggered by ${{ github.actor }} 🚀

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  ODC_CURRENT_BRANCH: ${{ github.ref_name }}
  ODC_PR_TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Check code format
        run: mvn impsort:check formatter:validate

  pmd-scan:
    name: PMD Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Run PMD scan
        run: mvn pmd:check

  unit-test:
    name: Unit Test
    needs: [ check-format, pmd-scan ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Run unit test
        run: mvn clean install -Dmaven.test.skip=false -DfailIfNoTests=false

  calculate-version:
    name: Calculate Version Number
    needs: [ check-format, pmd-scan ]
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      odc_rpm_release_number: ${{ steps.calculate_version.outputs.odc_rpm_release_number }}
      odc_docker_image_tag: ${{ steps.calculate_version.outputs.odc_docker_image_tag }}
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Calculate version number
        id: calculate_version
        run: |
          odc_rpm_release_number=$(date +%Y%m%d%H%M%S)
          echo "odc_rpm_release_number=${odc_rpm_release_number}" >> $GITHUB_OUTPUT
          echo "odc_rpm_release_number=${odc_rpm_release_number}"
          branch_match_regex="^[0-9]\\.[0-9]\\.([0-9]{1,2}|x)_(release|dev)$"
          tag_prefix=`[[ "${{ env.ODC_CURRENT_BRANCH }}" =~ ${branch_match_regex} ]] && echo "test" || echo "dev"`
          odc_docker_image_tag="${tag_prefix}-$(cat distribution/odc-server-VER.txt)-${{ github.actor }}-${odc_rpm_release_number}"
          echo "odc_docker_image_tag=${odc_docker_image_tag}" >> $GITHUB_OUTPUT
          echo "odc_docker_image_tag=${odc_docker_image_tag}"

  build-x86_64:
    name: Build (x86_64)
    needs: [ unit-test, calculate-version ]
    runs-on: ubuntu-latest
    env:
      odc_rpm_release_number: ${{ needs.calculate-version.outputs.odc_rpm_release_number }}
      odc_docker_image_tag: ${{ needs.calculate-version.outputs.odc_docker_image_tag }}
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Package
        run: mvn clean package -Dmaven.test.skip=true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-jar
          path: target/demo-*-SNAPSHOT.jar
      - name: Build RPM (x86_64)
        run: |
          echo "Skip for now 🤪"
          echo "odc_rpm_release_number=${odc_rpm_release_number}"
      - name: Build Docker Image (x86_64)
        run: |
          echo "Skip for now 🤪"
          echo "odc_docker_image_tag=${odc_docker_image_tag}"

  build-rpm-aarch64:
    name: Build (aarch64)
    needs: [ unit-test, calculate-version ]
    runs-on: ubuntu-latest
    env:
      odc_rpm_release_number: ${{ needs.calculate-version.outputs.odc_rpm_release_number }}
      odc_docker_image_tag: ${{ needs.calculate-version.outputs.odc_docker_image_tag }}
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Build RPM (aarch64)
        run: |
          echo "Skip for now 🤪"
          echo "odc_rpm_release_number=${odc_rpm_release_number}"
      - name: Build Docker Image (aarch64)
        run: |
          echo "Skip for now 🤪"
          echo "odc_docker_image_tag=${odc_docker_image_tag}"
